# Introduction to numpy

In [1]:
import numpy as np

## Datatypes & Attributes

Numpy's main datatype is ndarray:

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### .shape

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

### .ndim

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

### .dtype

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

### .size

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

### type()

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Creating a dataframe in pandas from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays with functions

### .ones()

In [21]:
ones_array = np.ones((2, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

The default data type for the ones is float. we can change that as below:

In [23]:
ones_array = np.ones((2, 3), dtype=int)
ones_array

array([[1, 1, 1],
       [1, 1, 1]])

### .zeros()

In [25]:
zeros_array = np.zeros((2, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

The default data type for the ones is float. we can change that as below:

In [26]:
zeros_array = np.zeros((2, 3), dtype=int)
zeros_array

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
type(ones_array), type(zeros_array)

(numpy.ndarray, numpy.ndarray)

In [28]:
ones_array.dtype, zeros_array.dtype

(dtype('int32'), dtype('int32'))

### .arange(start, stop, step, dtype)

In [32]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

The default data type of .arange() is integer. we can change that as below:

In [33]:
range_array = np.arange(0, 10, 2, dtype=float)
range_array

array([0., 2., 4., 6., 8.])